# https://taskfile.dev/#/
# Usage:
#   - Install task: https://taskfile.dev/#/installation
#   - Run the commands:
#     - task bot:lint
#     - task bot:run
#     - task bot:build

version: '3'

includes:
  bot: ./Taskfile_{{OS}}.yml