name: Build (CI)

on:
  push:
    branches-ignore:
      - root
      - develop
      - main #TODO: uncomment when detekt is working again

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1

        with:
          java-version: 1.11

      - name: Gradle (Build)
        run: sh gradlew build
        
      - name: Create Issue on Failed workflow
        if: ${{ failure() }}
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Action Workflow Failed
          body: |
            ### Context
            [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
            Workflow name - `${{ github.workflow }}`
            Job -           `${{ github.job }}`
            status -        `${{ job.status }}`
          assignees: Jamalam360
      
      - name: Upload artifacts (Main JAR)
        uses: actions/upload-artifact@v2

        with:
          name: Main JAR
          path: build/libs/*-all.jar

      - name: Upload artifacts (JARs)
        uses: actions/upload-artifact@v2

        with:
          name: JARs
          path: build/libs/*.jar
